POST https://server-nodejs-sufg.onrender.com/videos
Content-Type: application/json;

{
  "title": "My Node",
  "description": "This is a description of my node video.",
  "duration": 120,
  "url": "http://example.com/my-node-video"
}


###

GET  https://server-nodejs-sufg.onrender.com/videos?search=Render
###

PUT https://server-nodejs-sufg.onrender.com/videos/cc68ee59-1d8e-4710-b4c0-ea00bb459a48
Content-Type: application/json;

{
  "title": "Video Nodes.js in Render.com",
  "description": "This video is about Node.js that's deployed on render.",
  "duration": 200,
  "url": "http://example.com/nodejs-video"
}


###


DELETE  https://server-nodejs-sufg.onrender.com/videos/4638c8e0-c370-4df4-b0a0-e5460ed966e2
